number = float(input())+0.0001
print("NOTAS:")
cem = int(number/100)
print(cem, "nota(s) de R$ 100.00")
resto = (number - cem *100)
cinquenta = int(resto/50)
print(cinquenta, "nota(s) de R$ 50.00")
resto = (number - ((cem *100) + (cinquenta * 50)))
vinte = int(resto/20)
print(vinte, "nota(s) de R$ 20.00")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20)))
dez = int(resto/10)
print(dez, "nota(s) de R$ 10.00")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20) + (dez * 10)))
cinco = int(resto/5)
print(cinco, "nota(s) de R$ 5.00")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20) + (dez * 10) + (cinco * 5)))
dois = int(resto/2)
print(dois, "nota(s) de R$ 2.00")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20) + (dez * 10) + (cinco * 5) + (dois * 2)))
print("MOEDAS:")
um = int(resto/1)
print(um, "moeda(s) de R$ 1.00")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20) + (dez * 10) + (cinco * 5) + (dois * 2) + (um * 1)))
cinquenta_centavos = int(resto/0.50)
print(cinquenta_centavos, "moeda(s) de R$ 0.50")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20) + (dez * 10) + (cinco * 5) + (dois * 2) + (um * 1) + (cinquenta_centavos * 0.50)))
vinte_e_cinco_centavos = int(resto/0.25)
print(vinte_e_cinco_centavos, "moeda(s) de R$ 0.25")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20) + (dez * 10) + (cinco * 5) + (dois * 2) + (um * 1) + (cinquenta_centavos * 0.50) + (vinte_e_cinco_centavos * 0.25)))
dez_centavos = int(resto/0.10)
print(dez_centavos, "moeda(s) de R$ 0.10")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20) + (dez * 10) + (cinco * 5) + (dois * 2) + (um * 1) + (cinquenta_centavos * 0.50) + (vinte_e_cinco_centavos * 0.25) + (dez_centavos * 0.10)))
cinco_centavos = int(resto/0.05)
print(cinco_centavos, "moeda(s) de R$ 0.05")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20) + (dez * 10) + (cinco * 5) + (dois * 2) + (um * 1) + (cinquenta_centavos * 0.50) + (vinte_e_cinco_centavos * 0.25) + (dez_centavos * 0.10) + (cinco_centavos * 0.5)))
um_centavos = int(resto/0.01)
print(um_centavos, "moeda(s) de R$ 0.01")