number =int(input())
print(number)
cem = int(number/100)
print(cem, "nota(s) de R$ 100,00")
resto = (number - cem *100)
cinquenta = int(resto/50)
print(cinquenta, "nota(s) de R$ 50,00")
resto = (number - ((cem *100) + (cinquenta * 50)))
vinte = int(resto/20)
print(vinte, "nota(s) de R$ 20,00")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20)))
dez = int(resto/10)
print(dez, "nota(s) de R$ 10,00")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20) + (dez * 10)))
cinco = int(resto/5)
print(cinco, "nota(s) de R$ 5,00")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20) + (dez * 10) + (cinco * 5)))
dois = int(resto/2)
print(dois, "nota(s) de R$ 2,00")
resto = (number - ((cem *100) + (cinquenta * 50) + (vinte * 20) + (dez * 10) + (cinco * 5) + (dois * 2)))
um = int(resto/1)
print(um, "nota(s) de R$ 1,00")